source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target :CocoaAsyncSocketTestsMac do
    platform :osx, '10.8'
    pod 'CocoaAsyncSocket', :path => '../../CocoaAsyncSocket.podspec'
end