source 'https://github.com/CocoaPods/Specs.git'

ENV["COCOAPODS_DISABLE_STATS"] = "true"

use_frameworks!

target :CocoaAsyncSocketTestsMac do
    platform :osx, '10.8'
    pod 'CocoaAsyncSocket', :path => '../../CocoaAsyncSocket.podspec'
end