source 'https://github.com/CocoaPods/Specs.git'

target :CocoaAsyncSocketTestsMac do
    platform :osx, '10.7'
    pod 'CocoaAsyncSocket', :path => '../CocoaAsyncSocket.podspec'
end

target :CocoaAsyncSocketTestsiOS do
    platform :ios, '5.0'
    pod 'CocoaAsyncSocket', :path => '../CocoaAsyncSocket.podspec'
end