source 'https://github.com/CocoaPods/Specs.git'

ENV["COCOAPODS_DISABLE_STATS"] = "true"

use_frameworks!

target :CocoaAsyncSocketTestsiOS do
    platform :ios, '8.0'
    pod 'CocoaAsyncSocket', :path => '../../CocoaAsyncSocket.podspec'
end